### ISSUE TITLE
Any method get account name?

### ISSUE THREAD

**Issue by Lchiffon** [LyzandeR/RDota2#2]
Nice package!

Is there any method to get the name of the account?

There's only account id in the get_match_details function.

**Comment by LyzandeR** [comment]
Thanks @Lchiffon .

As far as I know SteamAPI does not share the account name only the ID. I guess you can find out some of the details (the documentation is not too accurate) [here](https://wiki.teamfortress.com/wiki/WebAPI/). If you are looking for a specific player, get the match ID from one of the games they played and check the player position (1-10) or hero ID to find out their account ID. Then you can use that in other function calls.

**Comment by Lchiffon** [comment]
Thanks~
